export const EXPEDITION_PACING_BALANCE = {
  // Opaque exploration should create uncertainty without turning every wave into a full map tour.
  baseExplorationChoices: 1,
  cartographerExplorationChoices: 3,
  explorationHpCutoffRatio: 0.42,
  normalMaxExplorationPath: 8,
  cartographerMaxExplorationPath: 14,
  normalMaxExplorationDetour: 5,
  cartographerMaxExplorationDetour: 9,
  explorationZonePriority: {
    defense: 34,
    secondary: 30,
    treasure: 24,
    antechamber: 18,
  },
  explorationPartyCartographerScoreBonus: 8,
  explorationCartographerSelfScoreBonus: 8,
  explorationPathPenalty: 1.15,
  explorationDetourPenalty: 0.9,
  roomEvaluationWarriorMs: 100,
  roomEvaluationDefaultMs: 180,
  roomEvaluationCartographerMs: 280,
  transitionWarriorRegroupMs: 120,
  transitionRegroupMs: 220,
  remainsWarriorReactionMs: 180,
  remainsReactionMs: 360,
  fleeTrapHesitationMs: 520,
  roomLockHesitationMs: 220,
  doorBlockedHesitationMs: 260,
  doorNoLockpicksHesitationMs: 520,
  doorBusyHesitationMs: 220,
  doorPickingPulseMs: 80,
  doorRetreatHesitationMs: 900,
  bossApproachWarriorMs: 120,
  bossPreparationMs: 230,
  bossStagingThiefMs: 220,
  bossStagingMs: 280,
} as const;

export const BALANCE_SMOKE_TARGETS = {
  maxGoldAfterTenWaves: 560,
  maxAverageDurationSeconds: 210,
  minAverageSurvivors: 1.4,
  maxKingdomFactsAfterTenWaves: 42,
  maxUnavailableSurvivorShare: 0.55,
  minReputationAfterLongrun: 22,
  minThreatAfterLongrun: 18,
  minReputationTierAfterLongrun: 2,
} as const;
