import type { AdventurerRole, DefenseType } from '../game/types';

export const TEXTURE_KEYS = {
  tileFloor: 'tile-floor',
  tileRock: 'tile-rock',
  tileRoom: 'tile-room',
  tileGuardRoom: 'tile-guard-room',
  tileCrypt: 'tile-crypt',
  tileTreasureRoom: 'tile-treasure-room',
  tileThroneRoom: 'tile-throne-room',
  tileEntry: 'tile-entry',
  tileTreasure: 'tile-treasure',
  tileBoss: 'tile-boss',
  door: 'door-reinforced',
  doorOpen: 'door-reinforced-open',
  boss: 'boss-final',
  bossAttack: 'boss-final-attack',
  decor: {
    transitionDown: 'decor-transition-down',
    transitionUp: 'decor-transition-up',
    treasureGold: 'decor-treasure-gold',
    treasureWeapon: 'decor-treasure-weapon',
    treasureArmor: 'decor-treasure-armor',
    treasureTechnique: 'decor-treasure-technique',
    remains: 'decor-remains',
    relic: 'decor-relic',
  },
  defense: {
    spikeTrap: 'defense-spike-trap',
    fireTrap: 'defense-fire-trap',
    roomLockTrap: 'defense-room-lock-trap',
    slime: 'defense-slime',
    skeleton: 'defense-skeleton',
    goblin: 'defense-goblin',
    guardian: 'defense-guardian',
  } satisfies Record<DefenseType, string>,
  adventurer: {
    warrior: 'adventurer-warrior',
    thief: 'adventurer-thief',
    mage: 'adventurer-mage',
    healer: 'adventurer-healer',
    cartographer: 'adventurer-cartographer',
  } satisfies Record<AdventurerRole, string>,
} as const;

export const EXTERNAL_TEXTURES: Array<{ key: string; path: string }> = [
  { key: TEXTURE_KEYS.tileFloor, path: '/assets/generated/dark-dungeon/floor.png' },
  { key: TEXTURE_KEYS.tileRock, path: '/assets/generated/dark-dungeon/rock.png' },
  { key: TEXTURE_KEYS.tileRoom, path: '/assets/generated/dark-dungeon/room.png' },
  { key: TEXTURE_KEYS.tileGuardRoom, path: '/assets/generated/dark-dungeon/guard-room.png' },
  { key: TEXTURE_KEYS.tileCrypt, path: '/assets/generated/dark-dungeon/crypt.png' },
  { key: TEXTURE_KEYS.tileTreasureRoom, path: '/assets/generated/dark-dungeon/treasure-room.png' },
  { key: TEXTURE_KEYS.tileThroneRoom, path: '/assets/generated/dark-dungeon/throne-room.png' },
  { key: TEXTURE_KEYS.tileEntry, path: '/assets/generated/dark-dungeon/entry.png' },
  { key: TEXTURE_KEYS.tileTreasure, path: '/assets/generated/dark-dungeon/treasure-room.png' },
  { key: TEXTURE_KEYS.tileBoss, path: '/assets/generated/dark-dungeon/throne-room.png' },
  { key: TEXTURE_KEYS.door, path: '/assets/generated/dark-dungeon/door-closed.png' },
  { key: TEXTURE_KEYS.doorOpen, path: '/assets/generated/dark-dungeon/door-open.png' },
  { key: TEXTURE_KEYS.decor.transitionDown, path: '/assets/generated/dark-dungeon/stairs-down.png' },
  { key: TEXTURE_KEYS.decor.transitionUp, path: '/assets/generated/dark-dungeon/stairs-up.png' },
  { key: TEXTURE_KEYS.decor.treasureGold, path: '/assets/generated/dark-dungeon/treasure-gold.png' },
  { key: TEXTURE_KEYS.decor.treasureWeapon, path: '/assets/generated/dark-dungeon/treasure-weapon.png' },
  { key: TEXTURE_KEYS.decor.treasureArmor, path: '/assets/generated/dark-dungeon/treasure-armor.png' },
  { key: TEXTURE_KEYS.decor.treasureTechnique, path: '/assets/generated/dark-dungeon/treasure-technique.png' },
  { key: TEXTURE_KEYS.decor.remains, path: '/assets/generated/dark-dungeon/remains.png' },
  { key: TEXTURE_KEYS.decor.relic, path: '/assets/generated/dark-dungeon/relic.png' },
  { key: TEXTURE_KEYS.defense.spikeTrap, path: '/assets/generated/dark-dungeon/spike-trap.png' },
  { key: TEXTURE_KEYS.defense.fireTrap, path: '/assets/generated/dark-dungeon/fire-trap.png' },
  { key: TEXTURE_KEYS.defense.roomLockTrap, path: '/assets/generated/dark-dungeon/room-lock-trap.png' },
];

export interface SpriteSheetAsset {
  key: string;
  path: string;
  frameWidth: number;
  frameHeight: number;
}

export const SPRITESHEET_ASSETS: SpriteSheetAsset[] = [
  { key: TEXTURE_KEYS.adventurer.warrior, path: '/assets/generated/roles/warrior.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.adventurer.thief, path: '/assets/generated/roles/thief.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.adventurer.mage, path: '/assets/generated/roles/mage.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.adventurer.healer, path: '/assets/generated/roles/healer.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.adventurer.cartographer, path: '/assets/generated/roles/cartographer.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.boss, path: '/assets/vendor/opengameart/warlocks-gauntlet/demon.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.bossAttack, path: '/assets/vendor/opengameart/warlocks-gauntlet/demon.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.defense.slime, path: '/assets/vendor/opengameart/warlocks-gauntlet/hornet-move.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.defense.skeleton, path: '/assets/vendor/opengameart/warlocks-gauntlet/skeleton-mage.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.defense.goblin, path: '/assets/vendor/opengameart/warlocks-gauntlet/timberman-move.png', frameWidth: 64, frameHeight: 64 },
  { key: TEXTURE_KEYS.defense.guardian, path: '/assets/vendor/opengameart/warlocks-gauntlet/gargant-lord-move.png', frameWidth: 64, frameHeight: 64 },
];

export const AUDIO_KEYS = {
  ambience: {
    dungeon: 'ambience-dungeon',
    deep: 'ambience-deep',
    tavern: 'ambience-tavern',
    boss: 'music-boss',
    guardian: 'music-guardian',
  },
  combat: {
    melee: ['sfx-melee-1', 'sfx-melee-2', 'sfx-melee-3'],
    hit: ['sfx-hit-1', 'sfx-hit-2', 'sfx-hit-3', 'sfx-hit-4'],
    armor: ['sfx-armor-1', 'sfx-armor-2', 'sfx-armor-3'],
    death: ['sfx-death-1', 'sfx-death-2'],
    slime: ['sfx-slime-1', 'sfx-slime-2', 'sfx-slime-3'],
  },
  magic: {
    cast: ['sfx-magic-cast-1', 'sfx-magic-cast-2'],
    fire: ['sfx-magic-fire-1', 'sfx-magic-fire-2', 'sfx-magic-fire-3'],
    heal: ['sfx-magic-heal-1', 'sfx-magic-heal-2'],
  },
  boss: {
    attack: ['sfx-boss-attack-1', 'sfx-boss-attack-2'],
    roar: ['sfx-boss-roar-1', 'sfx-boss-roar-2', 'sfx-boss-roar-3'],
  },
  doors: {
    open: ['sfx-door-open-1', 'sfx-door-open-2'],
    close: ['sfx-door-close-1', 'sfx-door-close-2'],
    lock: ['sfx-door-lock-1', 'sfx-door-lock-2'],
    pick: ['sfx-door-pick-1', 'sfx-door-pick-2'],
  },
  traps: {
    trigger: ['sfx-trap-trigger-1', 'sfx-trap-trigger-2', 'sfx-trap-trigger-3'],
    roomLock: ['sfx-room-lock-1', 'sfx-room-lock-2', 'sfx-room-lock-3'],
    disarm: ['sfx-trap-disarm-1', 'sfx-trap-disarm-2'],
  },
  loot: {
    coins: ['sfx-loot-coins-1', 'sfx-loot-coins-2', 'sfx-loot-coins-3'],
    special: ['sfx-loot-special-1', 'sfx-loot-special-2'],
  },
  ui: {
    click: ['sfx-ui-click-1', 'sfx-ui-click-2'],
    select: ['sfx-ui-select-1', 'sfx-ui-select-2'],
    confirm: ['sfx-ui-confirm-1', 'sfx-ui-confirm-2'],
    error: ['sfx-ui-error-1', 'sfx-ui-error-2'],
    toggle: ['sfx-ui-toggle-1'],
  },
  footsteps: ['sfx-footstep-1', 'sfx-footstep-2', 'sfx-footstep-3', 'sfx-footstep-4', 'sfx-footstep-5'],
  interaction: {
    stone: ['sfx-stone-1', 'sfx-stone-2'],
    wood: ['sfx-wood-1', 'sfx-wood-2'],
    paper: ['sfx-paper-1', 'sfx-paper-2'],
  },
  construction: {
    dig: ['sfx-dig-1', 'sfx-dig-2', 'sfx-dig-3'],
  },
} as const;

export const AUDIO_ASSETS: Array<{ key: string; path: string }> = [
  { key: AUDIO_KEYS.ambience.dungeon, path: '/assets/audio/ambience/dungeon_ambient_1.ogg' },
  { key: AUDIO_KEYS.ambience.deep, path: '/assets/audio/ambience/dark_cavern_ambient_002.ogg' },
  { key: AUDIO_KEYS.ambience.tavern, path: '/assets/audio/tavern/The_Old_Tower_Inn.mp3' },
  { key: AUDIO_KEYS.ambience.boss, path: '/assets/audio/music/epic_boss_battle_loop.wav' },
  { key: AUDIO_KEYS.ambience.guardian, path: '/assets/audio/music/guardian_battle_theme.mp3' },
  { key: AUDIO_KEYS.combat.melee[0], path: '/assets/audio/combat/blade_01.ogg' },
  { key: AUDIO_KEYS.combat.melee[1], path: '/assets/audio/combat/blade_02.ogg' },
  { key: AUDIO_KEYS.combat.melee[2], path: '/assets/audio/combat/knifeSlice.ogg' },
  { key: AUDIO_KEYS.combat.hit[0], path: '/assets/audio/combat/impactPunch_medium_000.ogg' },
  { key: AUDIO_KEYS.combat.hit[1], path: '/assets/audio/combat/impactPunch_medium_001.ogg' },
  { key: AUDIO_KEYS.combat.hit[2], path: '/assets/audio/combat/impactGeneric_light_000.ogg' },
  { key: AUDIO_KEYS.combat.hit[3], path: '/assets/audio/combat/creature_hurt_01.ogg' },
  { key: AUDIO_KEYS.combat.armor[0], path: '/assets/audio/combat/impactMetal_medium_000.ogg' },
  { key: AUDIO_KEYS.combat.armor[1], path: '/assets/audio/combat/impactMetal_medium_001.ogg' },
  { key: AUDIO_KEYS.combat.armor[2], path: '/assets/audio/combat/impactMetal_heavy_000.ogg' },
  { key: AUDIO_KEYS.combat.death[0], path: '/assets/audio/combat/creature_die_01.ogg' },
  { key: AUDIO_KEYS.combat.death[1], path: '/assets/audio/combat/creature_hurt_02.ogg' },
  { key: AUDIO_KEYS.combat.slime[0], path: '/assets/audio/combat/creature_slime_01.ogg' },
  { key: AUDIO_KEYS.combat.slime[1], path: '/assets/audio/combat/creature_slime_02.ogg' },
  { key: AUDIO_KEYS.combat.slime[2], path: '/assets/audio/combat/creature_slime_03.ogg' },
  { key: AUDIO_KEYS.magic.cast[0], path: '/assets/audio/magic/spell_01.ogg' },
  { key: AUDIO_KEYS.magic.cast[1], path: '/assets/audio/magic/spell_02.ogg' },
  { key: AUDIO_KEYS.magic.fire[0], path: '/assets/audio/magic/spell_fire_01.ogg' },
  { key: AUDIO_KEYS.magic.fire[1], path: '/assets/audio/magic/spell_fire_02.ogg' },
  { key: AUDIO_KEYS.magic.fire[2], path: '/assets/audio/magic/spell_fire_03.ogg' },
  { key: AUDIO_KEYS.magic.heal[0], path: '/assets/audio/magic/spell_01.ogg' },
  { key: AUDIO_KEYS.magic.heal[1], path: '/assets/audio/magic/spell_02.ogg' },
  { key: AUDIO_KEYS.boss.attack[0], path: '/assets/audio/boss/creature_monster_01.ogg' },
  { key: AUDIO_KEYS.boss.attack[1], path: '/assets/audio/boss/creature_monster_02.ogg' },
  { key: AUDIO_KEYS.boss.roar[0], path: '/assets/audio/boss/creature_roar_01.ogg' },
  { key: AUDIO_KEYS.boss.roar[1], path: '/assets/audio/boss/creature_roar_02.ogg' },
  { key: AUDIO_KEYS.boss.roar[2], path: '/assets/audio/boss/creature_roar_03.ogg' },
  { key: AUDIO_KEYS.doors.open[0], path: '/assets/audio/doors/doorOpen_1.ogg' },
  { key: AUDIO_KEYS.doors.open[1], path: '/assets/audio/doors/doorOpen_2.ogg' },
  { key: AUDIO_KEYS.doors.close[0], path: '/assets/audio/doors/doorClose_1.ogg' },
  { key: AUDIO_KEYS.doors.close[1], path: '/assets/audio/doors/doorClose_2.ogg' },
  { key: AUDIO_KEYS.doors.lock[0], path: '/assets/audio/doors/metalLatch.ogg' },
  { key: AUDIO_KEYS.doors.lock[1], path: '/assets/audio/doors/metalClick.ogg' },
  { key: AUDIO_KEYS.doors.pick[0], path: '/assets/audio/traps/lock_01.ogg' },
  { key: AUDIO_KEYS.doors.pick[1], path: '/assets/audio/traps/lock_02.ogg' },
  { key: AUDIO_KEYS.traps.trigger[0], path: '/assets/audio/traps/chain_01.ogg' },
  { key: AUDIO_KEYS.traps.trigger[1], path: '/assets/audio/traps/chain_02.ogg' },
  { key: AUDIO_KEYS.traps.trigger[2], path: '/assets/audio/traps/lock_03.ogg' },
  { key: AUDIO_KEYS.traps.roomLock[0], path: '/assets/audio/traps/chain_01.ogg' },
  { key: AUDIO_KEYS.traps.roomLock[1], path: '/assets/audio/traps/chain_02.ogg' },
  { key: AUDIO_KEYS.traps.roomLock[2], path: '/assets/audio/traps/chain_03.ogg' },
  { key: AUDIO_KEYS.traps.disarm[0], path: '/assets/audio/doors/metalClick.ogg' },
  { key: AUDIO_KEYS.traps.disarm[1], path: '/assets/audio/traps/lock_02.ogg' },
  { key: AUDIO_KEYS.loot.coins[0], path: '/assets/audio/loot/item_coins_01.ogg' },
  { key: AUDIO_KEYS.loot.coins[1], path: '/assets/audio/loot/item_coins_02.ogg' },
  { key: AUDIO_KEYS.loot.coins[2], path: '/assets/audio/loot/handleCoins.ogg' },
  { key: AUDIO_KEYS.loot.special[0], path: '/assets/audio/loot/item_gem_01.ogg' },
  { key: AUDIO_KEYS.loot.special[1], path: '/assets/audio/loot/item_gem_02.ogg' },
  { key: AUDIO_KEYS.ui.click[0], path: '/assets/audio/ui/click_001.ogg' },
  { key: AUDIO_KEYS.ui.click[1], path: '/assets/audio/ui/click_002.ogg' },
  { key: AUDIO_KEYS.ui.select[0], path: '/assets/audio/ui/select_001.ogg' },
  { key: AUDIO_KEYS.ui.select[1], path: '/assets/audio/ui/select_002.ogg' },
  { key: AUDIO_KEYS.ui.confirm[0], path: '/assets/audio/ui/confirmation_001.ogg' },
  { key: AUDIO_KEYS.ui.confirm[1], path: '/assets/audio/ui/confirmation_002.ogg' },
  { key: AUDIO_KEYS.ui.error[0], path: '/assets/audio/ui/error_001.ogg' },
  { key: AUDIO_KEYS.ui.error[1], path: '/assets/audio/ui/error_002.ogg' },
  { key: AUDIO_KEYS.ui.toggle[0], path: '/assets/audio/ui/toggle_001.ogg' },
  { key: AUDIO_KEYS.footsteps[0], path: '/assets/audio/footsteps/footstep_concrete_000.ogg' },
  { key: AUDIO_KEYS.footsteps[1], path: '/assets/audio/footsteps/footstep_concrete_001.ogg' },
  { key: AUDIO_KEYS.footsteps[2], path: '/assets/audio/footsteps/footstep00.ogg' },
  { key: AUDIO_KEYS.footsteps[3], path: '/assets/audio/footsteps/footstep01.ogg' },
  { key: AUDIO_KEYS.footsteps[4], path: '/assets/audio/footsteps/footstep02.ogg' },
  { key: AUDIO_KEYS.interaction.stone[0], path: '/assets/audio/interaction/stones_01.ogg' },
  { key: AUDIO_KEYS.interaction.stone[1], path: '/assets/audio/interaction/stones_02.ogg' },
  { key: AUDIO_KEYS.interaction.wood[0], path: '/assets/audio/interaction/wood_01.ogg' },
  { key: AUDIO_KEYS.interaction.wood[1], path: '/assets/audio/interaction/wood_02.ogg' },
  { key: AUDIO_KEYS.interaction.paper[0], path: '/assets/audio/interaction/bookFlip1.ogg' },
  { key: AUDIO_KEYS.interaction.paper[1], path: '/assets/audio/interaction/bookOpen.ogg' },
  { key: AUDIO_KEYS.construction.dig[0], path: '/assets/audio/construction/impactMining_000.ogg' },
  { key: AUDIO_KEYS.construction.dig[1], path: '/assets/audio/construction/impactMining_001.ogg' },
  { key: AUDIO_KEYS.construction.dig[2], path: '/assets/audio/construction/impactMining_002.ogg' },
];
